### ISSUE TITLE
EPIC 2 of 2: Productionise

### ISSUE THREAD

**Issue by mikeAdamss** [ONS-OpenData/dp-opendata-upload#11]
Everything from EPIC 1 is perfectly viable and gets us too (and lets us work out the kinks) of a working thing in develop.

Once we're happy we need to:

- [ ] Test coverage so the working things keep working.
- [ ] Write the infrastructure creation bits in terraform.
- [ ] Add some CI for deploying the lambda code as per typical services.

point 2 and 3 may be more one for the website devops team, should probably discuss at the time.
