### ISSUE TITLE
EPIC 1 of 2: mvp/poc checklist

### ISSUE THREAD

**Issue by mikeAdamss** [ONS-OpenData/dp-opendata-upload#4]
A checklist representing all the things we'd need to do to create a working minimal viable product / proof of concept.

For this stage, adding resources via the AWS UI is fine, we'll handle infrastructure as code and proper CI as part of EPIC 2 of 2.

**Admin tasks:**

- [ ] Verified commits (Mike)
- [ ] Verified commits (Jim)

**Decisions**

- [ ] Whats the entry point (standard way of starting) a transform? Write it up, put it in `./documentation/transforms.md`. @JimBryant7 

**Basic Deployment/CI**

- [ ] Some sort of minimum "good enough for poc" deployment method for lambdas, probably a shell script, possbily [https://github.com/Miserlou/Zappa](https://github.com/Miserlou/Zappa). @mikeAdamss 

**Static AWS Resources**

- [ ] Create `sns-opendata-transform-topic`, via the AWS UI is fine.
- [ ] Create `sns-opendata-transform-topic-persistent` via the AWS UI is fine.
- [ ] Create Restful API gateway `api-opendata-dataset-details` via the AWS UI is fine.

**Write the following lambdas**

- [ ] dp-transform-decision-lambda https://github.com/ONS-OpenData/dp-opendata-upload/issues/3
- [ ] dp-transform-details-lambda https://github.com/ONS-OpenData/dp-opendata-upload/issues/1
- [ ] dp-transformer-lambda
- [ ] dp-v4-automated-upload
- [ ] dp-v4-automated-upload-metadata-parser
